In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('equipment_data.csv')

In [3]:
df.head()  # Display the first few rows of the dataframe

,Timestamp,Temperature (째C),Vibration (mm/s),Pressure (Pa),RPM,Maintenance Required,Temp_Change,Vib_Change
0,2019-01-01 00:00:00,0.548793,0.509840,0.619918,0.741161,1,0.501129,0.499619
1,2019-01-01 01:00:00,0.715185,0.587573,0.802121,0.292862,1,0.584882,0.538630
2,2019-01-01 02:00:00,0.602748,0.294453,0.965546,0.624416,1,0.444534,0.352514
3,2019-01-01 03:00:00,0.544862,0.500041,0.519955,0.931955,0,0.471992,0.602794
4,2019-01-01 04:00:00,0.423622,0.031649,0.323663,0.799867,0,0.440103,0.264552

In [4]:
df.describe()  # Get a statistical summary of the dataframe

,Temperature (째C),Vibration (mm/s),Pressure (Pa),RPM,Maintenance Required,Temp_Change,Vib_Change
count,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000
mean,0.497752,0.500139,0.502902,0.500764,0.500776,0.501133,0.499622
std,0.289543,0.288612,0.289589,0.288880,0.500005,0.206076,0.205033
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.246304,0.248662,0.250924,0.250167,0.000000,0.352515,0.352197
50%,0.497589,0.500018,0.504503,0.503002,1.000000,0.501690,0.498956
75%,0.749073,0.749795,0.755002,0.749166,1.000000,0.649000,0.647563
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
df.isnull().sum()  # Check for missing values in the dataframe

Timestamp               0
Temperature (째C)        0
Vibration (mm/s)        0
Pressure (Pa)           0
RPM                     0
Maintenance Required    0
Temp_Change             0
Vib_Change              0
dtype: int64

In [ ]:
df.corr()  # Get the correlation matrix of the dataframe

ValueError: could not convert string to float: '2019-01-01 00:00:00'

In [8]:
df_new = df.drop(columns= ['Timestamp'])

In [9]:
df_new.corr()  # Get the correlation matrix of the new dataframe without 'Timestamp'

,Temperature (째C),Vibration (mm/s),Pressure (Pa),RPM,Maintenance Required,Temp_Change,Vib_Change
Temperature (째C),1.000000,-0.004103,0.000167,-0.004175,-0.001307,0.707008,-0.006027
Vibration (mm/s),-0.004103,1.000000,-0.004749,-0.009567,0.004426,0.006849,0.707790
Pressure (Pa),0.000167,-0.004749,1.000000,-0.001053,0.002288,0.001684,0.002775
RPM,-0.004175,-0.009567,-0.001053,1.000000,-0.002704,-0.002509,-0.013184
Maintenance Required,-0.001307,0.004426,0.002288,-0.002704,1.000000,-0.002828,-0.001669
Temp_Change,0.707008,0.006849,0.001684,-0.002509,-0.002828,1.000000,0.000559
Vib_Change,-0.006027,0.707790,0.002775,-0.013184,-0.001669,0.000559,1.000000